name: sailors
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_hooks: ^0.21.2
  get_it: ^8.0.3
  retrofit: ^4.1.0
  floor: ^1.4.2
  flutter_bloc: ^9.1.0
  equatable: ^2.0.5
  dio: ^5.4.1
  bloc: ^9.0.0
  ionicons: ^0.2.2
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  motion_toast: ^2.7.5
  flutter_svg: ^2.0.7
  flutter_secure_storage: ^9.0.0
  easy_localization: ^3.0.7+1
  easy_localization_loader: ^2.0.2
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  retrofit_generator: ^9.1.9
  easy_localization_generator: ^0.3.3


flutter:
  uses-material-design: true
  assets:
    - images/dummy.png
    - images/ic_logo.png
    - images/ad_icon.svg
    - images/add_ad_icon.svg
    - images/home_icon.svg
    - images/notification_icon.svg
    - images/profile_icon.svg
    - images/back_icon.svg
    - images/settings_icon.svg
    - images/settings_about_app_icon.svg
    - images/settings_change_password_icon.svg
    - images/settings_contact_us_icon.svg
    - images/settings_profile_icon.svg
    - images/settings_report_icon.svg
    - images/whatsapp_icon.svg
    - images/tiktok_icon.svg
    - images/facebook_icon.svg
    - i18n/en.json
    - i18n/ar.json
  fonts:
    - family: SailorLight
      fonts:
        - asset: fonts/light.ttf

    - family: SailorRegular
      fonts:
        - asset: fonts/regular.ttf

    - family: SailorMedium
      fonts:
        - asset: fonts/medium.ttf

    - family: SailorBold
      fonts:
        - asset: fonts/bold.ttf

    - family: SailorExtraBold
      fonts:
        - asset: fonts/extra_bold.ttf

    - family: SailorBlack
      fonts:
        - asset: fonts/black.ttf