name: sailors
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_hooks: ^0.21.2
  get_it: ^8.0.3
  retrofit: ^4.1.0
  floor: ^1.4.2
  flutter_bloc: ^9.1.0
  equatable: ^2.0.5
  dio: ^5.4.1
  bloc: ^9.0.0
  ionicons: ^0.2.2
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  motion_toast: ^2.7.5
  easy_localization: ^3.0.3
  flutter_svg: ^2.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  retrofit_generator: ^9.1.9

flutter:
  uses-material-design: true
  assets:
    - images/dummy.png
    - images/ic_logo.png
    - images/ad_icon.svg
    - images/add_ad_icon.svg
    - images/home_icon.svg
    - images/notification_icon.svg
    - images/profile_icon.svg
    - images/back_icon.svg
    - i18n/en.json
    - i18n/ar.json
  fonts:
    - family: Sailor
      fonts:
        - asset: fonts/light.ttf
          weight: 300
        - asset: fonts/regular.ttf
          weight: 400
        - asset: fonts/medium.ttf
          weight: 500
        - asset: fonts/bold.ttf
          weight: 700
        - asset: fonts/extra_bold.ttf
          weight: 800
        - asset: fonts/black.ttf
          weight: 900
